<?php

declare(strict_types=1);

namespace Hydra\Database\Contracts;

/**
 * The database seam.
 *
 * A thin, prepared-statement-only surface over whatever driver sits behind it
 * ({@see \Hydra\Database\PdoConnection} today). Repositories depend on this
 * interface, not on PDO, so the engine is swappable the same way
 * {@see \Hydra\View\Contracts\ViewInterface} makes the template engine
 * swappable. No query builder, no ORM — repositories write their own SQL and
 * pass bound parameters.
 */
interface ConnectionInterface
{
    /**
     * Run a query and return every row as an associative array.
     *
     * @param list<mixed> $params Bound to the statement's placeholders.
     * @return list<array<string, mixed>>
     */
    public function select(string $sql, array $params = []): array;

    /**
     * Run a query and return the first row, or null if there are none.
     *
     * @param list<mixed> $params
     * @return array<string, mixed>|null
     */
    public function selectOne(string $sql, array $params = []): ?array;

    /**
     * Run a write (INSERT/UPDATE/DELETE) and return the affected row count.
     *
     * @param list<mixed> $params
     */
    public function execute(string $sql, array $params = []): int;

    /** The id generated by the most recent INSERT on this connection. */
    public function lastInsertId(): int;
}
